[2024-02-13T10:07:01.144+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deverlop_model.data_sets scheduled__2024-02-11T11:21:00+00:00 [queued]>
[2024-02-13T10:07:01.155+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deverlop_model.data_sets scheduled__2024-02-11T11:21:00+00:00 [queued]>
[2024-02-13T10:07:01.156+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T10:07:01.172+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): data_sets> on 2024-02-11 11:21:00+00:00
[2024-02-13T10:07:01.182+0000] {standard_task_runner.py:60} INFO - Started process 1344 to run task
[2024-02-13T10:07:01.185+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deverlop_model', 'data_sets', 'scheduled__2024-02-11T11:21:00+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpbdi48r8u']
[2024-02-13T10:07:01.188+0000] {standard_task_runner.py:88} INFO - Job 190: Subtask data_sets
[2024-02-13T10:07:01.238+0000] {task_command.py:423} INFO - Running <TaskInstance: deverlop_model.data_sets scheduled__2024-02-11T11:21:00+00:00 [running]> on host 292a13d21cb7
[2024-02-13T10:07:01.343+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rtn' AIRFLOW_CTX_DAG_ID='deverlop_model' AIRFLOW_CTX_TASK_ID='data_sets' AIRFLOW_CTX_EXECUTION_DATE='2024-02-11T11:21:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-11T11:21:00+00:00'
[2024-02-13T10:07:01.370+0000] {docker.py:359} INFO - Starting docker container from image python:3.8
[2024-02-13T10:07:03.711+0000] {docker.py:429} INFO - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2024-02-13T10:07:04.000+0000] {docker.py:429} INFO - [notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[2024-02-13T10:07:09.206+0000] {docker.py:429} INFO - READ DATA :  HELLO WORLD  timestamp :  2024-02-13 10:07:09.198591
[2024-02-13T10:07:09.789+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deverlop_model, task_id=data_sets, execution_date=20240211T112100, start_date=20240213T100701, end_date=20240213T100709
[2024-02-13T10:07:09.931+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-13T10:07:09.959+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
