[2024-02-14T02:54:50.704+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deverlop_model.StartJob manual__2024-02-14T02:54:48.936784+00:00 [queued]>
[2024-02-14T02:54:50.711+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deverlop_model.StartJob manual__2024-02-14T02:54:48.936784+00:00 [queued]>
[2024-02-14T02:54:50.711+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-14T02:54:50.722+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): StartJob> on 2024-02-14 02:54:48.936784+00:00
[2024-02-14T02:54:50.728+0000] {standard_task_runner.py:60} INFO - Started process 1536 to run task
[2024-02-14T02:54:50.731+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deverlop_model', 'StartJob', 'manual__2024-02-14T02:54:48.936784+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpsx18o4pv']
[2024-02-14T02:54:50.733+0000] {standard_task_runner.py:88} INFO - Job 153: Subtask StartJob
[2024-02-14T02:54:50.771+0000] {task_command.py:423} INFO - Running <TaskInstance: deverlop_model.StartJob manual__2024-02-14T02:54:48.936784+00:00 [running]> on host 6e2ff7d2ffd0
[2024-02-14T02:54:50.835+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rtn' AIRFLOW_CTX_DAG_ID='deverlop_model' AIRFLOW_CTX_TASK_ID='StartJob' AIRFLOW_CTX_EXECUTION_DATE='2024-02-14T02:54:48.936784+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-14T02:54:48.936784+00:00'
[2024-02-14T02:54:50.837+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-14T02:54:50.838+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo StartJob && mkdir /***_base/dags/data/2024-02-14 02:54:49.896016/']
[2024-02-14T02:54:50.850+0000] {subprocess.py:86} INFO - Output:
[2024-02-14T02:54:50.851+0000] {subprocess.py:93} INFO - StartJob
[2024-02-14T02:54:50.853+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/***_base/dags/data/2024-02-14’: No such file or directory
[2024-02-14T02:54:50.854+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-14T02:54:50.863+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-14T02:54:50.866+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=deverlop_model, task_id=StartJob, execution_date=20240214T025448, start_date=20240214T025450, end_date=20240214T025450
[2024-02-14T02:54:50.876+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 153 for task StartJob (Bash command failed. The command returned a non-zero exit code 1.; 1536)
[2024-02-14T02:54:50.904+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-14T02:54:50.928+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
