[2024-02-13T18:10:15.330+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T18:05:00+00:00 [queued]>
[2024-02-13T18:10:15.337+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T18:05:00+00:00 [queued]>
[2024-02-13T18:10:15.337+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T18:10:15.364+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): data_sets> on 2024-02-13 18:05:00+00:00
[2024-02-13T18:10:15.371+0000] {standard_task_runner.py:60} INFO - Started process 125 to run task
[2024-02-13T18:10:15.373+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deverlop_model', 'data_sets', 'scheduled__2024-02-13T18:05:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpdsp5yda1']
[2024-02-13T18:10:15.376+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask data_sets
[2024-02-13T18:10:15.421+0000] {task_command.py:423} INFO - Running <TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T18:05:00+00:00 [running]> on host 4a5aad6d7b9e
[2024-02-13T18:10:15.518+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rtn' AIRFLOW_CTX_DAG_ID='deverlop_model' AIRFLOW_CTX_TASK_ID='data_sets' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T18:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-13T18:05:00+00:00'
[2024-02-13T18:10:15.584+0000] {docker.py:486} INFO - Pulling docker image python:3.8
[2024-02-13T18:10:24.263+0000] {docker.py:500} INFO - 3.8: Pulling from library/python
[2024-02-13T18:10:24.302+0000] {docker.py:500} INFO - 7bb465c29149: Already exists
[2024-02-13T18:10:24.321+0000] {docker.py:500} INFO - 2b9b41aaa3c5: Already exists
[2024-02-13T18:10:24.342+0000] {docker.py:500} INFO - 49b40be4436e: Pulling fs layer
[2024-02-13T18:10:24.343+0000] {docker.py:500} INFO - c558fac597f8: Pulling fs layer
[2024-02-13T18:10:24.343+0000] {docker.py:500} INFO - 11402150a57e: Pulling fs layer
[2024-02-13T18:10:24.344+0000] {docker.py:500} INFO - 4532b04ec8f7: Pulling fs layer
[2024-02-13T18:10:24.344+0000] {docker.py:500} INFO - 4df0efb76c10: Pulling fs layer
[2024-02-13T18:10:24.344+0000] {docker.py:500} INFO - 951fd003e72c: Pulling fs layer
[2024-02-13T18:10:24.345+0000] {docker.py:500} INFO - 951fd003e72c: Waiting
[2024-02-13T18:10:24.345+0000] {docker.py:500} INFO - 4532b04ec8f7: Download complete
[2024-02-13T18:10:24.346+0000] {docker.py:500} INFO - 4df0efb76c10: Waiting
[2024-02-13T18:10:24.346+0000] {docker.py:500} INFO - 49b40be4436e: Downloading
[2024-02-13T18:10:24.347+0000] {docker.py:500} INFO - c558fac597f8: Downloading
[2024-02-13T18:10:24.347+0000] {docker.py:500} INFO - 11402150a57e: Download complete
[2024-02-13T18:10:26.013+0000] {docker.py:500} INFO - 4df0efb76c10: Downloading
[2024-02-13T18:10:26.014+0000] {docker.py:500} INFO - 4df0efb76c10: Verifying Checksum
[2024-02-13T18:10:26.015+0000] {docker.py:500} INFO - 4df0efb76c10: Download complete
[2024-02-13T18:10:28.974+0000] {docker.py:500} INFO - 951fd003e72c: Downloading
[2024-02-13T18:10:34.201+0000] {docker.py:500} INFO - 951fd003e72c: Verifying Checksum
[2024-02-13T18:10:34.202+0000] {docker.py:500} INFO - 951fd003e72c: Download complete
[2024-02-13T18:11:00.160+0000] {docker.py:500} INFO - 49b40be4436e: Verifying Checksum
[2024-02-13T18:11:00.160+0000] {docker.py:500} INFO - 49b40be4436e: Download complete
[2024-02-13T18:11:00.283+0000] {docker.py:500} INFO - 49b40be4436e: Extracting
[2024-02-13T18:11:19.687+0000] {docker.py:500} INFO - 49b40be4436e: Pull complete
[2024-02-13T18:11:31.403+0000] {docker.py:500} INFO - c558fac597f8: Verifying Checksum
[2024-02-13T18:11:31.404+0000] {docker.py:500} INFO - c558fac597f8: Download complete
[2024-02-13T18:11:31.499+0000] {docker.py:500} INFO - c558fac597f8: Extracting
[2024-02-13T18:12:19.798+0000] {docker.py:500} INFO - c558fac597f8: Pull complete
[2024-02-13T18:12:19.806+0000] {docker.py:500} INFO - 11402150a57e: Extracting
[2024-02-13T18:12:20.127+0000] {docker.py:500} INFO - 11402150a57e: Pull complete
[2024-02-13T18:12:20.144+0000] {docker.py:500} INFO - 4532b04ec8f7: Extracting
[2024-02-13T18:12:20.767+0000] {docker.py:500} INFO - 4532b04ec8f7: Pull complete
[2024-02-13T18:12:20.771+0000] {docker.py:500} INFO - 4df0efb76c10: Extracting
[2024-02-13T18:12:20.792+0000] {docker.py:500} INFO - 4df0efb76c10: Pull complete
[2024-02-13T18:12:20.797+0000] {docker.py:500} INFO - 951fd003e72c: Extracting
[2024-02-13T18:12:21.095+0000] {docker.py:500} INFO - 951fd003e72c: Pull complete
[2024-02-13T18:12:21.123+0000] {docker.py:495} INFO - Digest: sha256:6150a41f1a0913ccbd5eb52fa12b90228e36286ef3255e6f5c5496d114ab955d
[2024-02-13T18:12:21.128+0000] {docker.py:495} INFO - Status: Downloaded newer image for python:3.8
[2024-02-13T18:12:21.134+0000] {docker.py:359} INFO - Starting docker container from image python:3.8
[2024-02-13T18:12:23.250+0000] {docker.py:429} INFO - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2024-02-13T18:12:23.551+0000] {docker.py:429} INFO - [notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[2024-02-13T18:12:28.645+0000] {docker.py:429} INFO - READ DATA :  HELLO WORLD  timestamp :  2024-02-13 18:12:28.641604
[2024-02-13T18:12:29.241+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deverlop_model, task_id=data_sets, execution_date=20240213T180500, start_date=20240213T181015, end_date=20240213T181229
[2024-02-13T18:12:29.303+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-13T18:12:29.331+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
